### ISSUE TITLE
Include Pydio Booster

### ISSUE THREAD

**Issue by mrjonny2** [linuxserver/docker-pydio#21]
Addition of Pydio booster to enable sockets and improve performance
[https://pydio.com/en/docs/v8/install-pydio-booster-manually](https://pydio.com/en/docs/v8/install-pydio-booster-manually)

**Comment by FourEyedPanda** [comment]
@mrjonny2 

Just an FYI I was able to get this to work. Unfortunately every time the docker updates it resets but, if you did have trouble getting it to work and just an additional FYI to the people maintaining it, I got it to work by:

Grab the latest booster here: https://download.pydio.com/pub/booster/release/
Probably automate this with a wget or something on first run and if there is a new one we have to update the link as there is no static link for the newest version...

I put it in /config/pydiobooster for example. We now need to create 2 files which sadly I don't think we can automate and would require the end user to create as it contains informations specfic to the environment. In the same folder make 2 files pydiocaddy and pydioconf:

See their format here: https://pydio.com/en/docs/v8/install-pydio-booster-manually
Make sure you read the whole thing so you know how to get your TOKENP and TOKENS so you can modify the files as needed and make sure to replace http:\/\/YOUR_HOSTNAME

Note: You may be using SSL and if you are a better way than reverse proxying it would be to just change the pydioconf file to use SSL. To do that change http://127.0.0.1:8090 {

to https://example.com:8090 (example.com being your domain)
and right under that on the next line:

tls /path/to/cert/fullchain.pem /path/to/cert/fullchain.pem 

so it should look like:

https://example.com:8090 {
	tls /path/to/cert/fullchain.pem /path/to/cert/fullchain.pem 
    pydiows /ws     {

(If you are using a letsencrypt docker you can add the letsencrypt appdata to your pydio one so it is automatically updated. Note: You must use the whole letsencrypt appdata folder as the one fullchain.pem and privkey.pem are links and not actual files and as such for the link to work you must use the whole appdata folder)

Now I am sure you can automate this in the docker init but, for now we need to run 

docker exec -it pydio bash 
to get to the dockers bash:

run the following commands:
apk update
apk upgrade
apk add su-exec
apk add libc6-compat

su-exec is so we can run it as abc which is what nginx is ran as and libc6-compat which took forever for me to figure out is required for pydiobooster to start.

Now mkdir /etc/services.d/pydiobooster

create a file named run in that folder with the contents (Note that the command is a bit different from the guide at pydio... it is a -conf instead of -c because -c is not an actual variable... and this once again took me forever to figure out):

#!/usr/bin/with-contenv bash
su-exec abc /config/pydiobooster/pydio -conf /config/pydiobooster/pydioconf

The above is needed to start pydiobooster on startup. Now the next time you start the docker pydiobooster will run automatically. Unforunately you need to do everything from apk update down again once the docker is updated unless it gets finally put in the init and the run file is created on init as well.

Unforutnately I don't see pydiobooster being included automagically due to all these manual steps. However what I would like to see is all the apk commands be done on init as well as the run file being created. There could also be a condition such as if /config/pydiobooster/pydio exists. I will assume you know how to setup everything else in the pydio web interface yourself.

Hope this helps you.

**Comment by thelamer** [comment]
Looking through how this is integrated it seems like a stopgap until it is ready to replace everything PHP currently does for the application. 

I would not expect this to be integrated into the Container until the Pydio developers make it the official web engine vs PHP and Nginx.
